# Generated by Django 5.2.9 on 2026-01-02 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('checklist_items', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_address', models.CharField(max_length=500)),
                ('responses', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectiontemplate')),
            ],
            options={
                'db_table': 'inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=255)),
                ('s3_url', models.URLField(max_length=1000)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspector', 'status'], name='inspections_inspect_940da1_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['created_at'], name='inspections_created_3c05b5_idx'),
        ),
    ]
