# Generated by Django 5.2.9 on 2026-01-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
