# Generated by Django 5.2.9 on 2026-01-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0003_delete_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="inspections.inspectiontemplate"),
        ),
    ]
