# Generated by Django 5.2.9 on 2026-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_inspection_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
