# Generated by Django 5.2.9 on 2026-02-04 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_version_number', models.IntegerField(blank=True, null=True)),
                ('server_version_number', models.IntegerField(blank=True, null=True)),
                ('client_data', models.JSONField(blank=True, help_text="Client's version of data", null=True)),
                ('server_data', models.JSONField(blank=True, help_text="Server's version of data", null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_strategy', models.CharField(blank=True, help_text='keep_mine, keep_theirs, merge', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='inspections.inspection')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conflict_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inspection'], name='conflict_re_inspect_394764_idx'), models.Index(fields=['resolved'], name='conflict_re_resolve_c48d97_idx'), models.Index(fields=['resolved', 'created_at'], name='conflict_re_resolve_47dc57_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Client-generated UUID for idempotency', max_length=255, unique=True)),
                ('operation_type', models.CharField(help_text='CREATE_INSPECTION, UPDATE_INSPECTION, etc.', max_length=50)),
                ('entity_id', models.UUIDField(help_text='ID of the entity being processed')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, help_text='Response data to return to client', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operations',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['idempotency_key'], name='sync_operat_idempot_4c82b8_idx'), models.Index(fields=['entity_id'], name='sync_operat_entity__810cbf_idx'), models.Index(fields=['user', 'processed_at'], name='sync_operat_user_id_b0de51_idx'), models.Index(fields=['operation_type', 'processed_at'], name='sync_operat_operati_5dd32c_idx')],
            },
        ),
    ]
