# Generated by Django 5.2.9 on 2026-01-21 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0003_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_url', models.URLField(max_length=1000)),
                ('file_size', models.IntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['inspection'], name='photos_inspect_747fea_idx')],
            },
        ),
    ]
