# Generated by Django 5.2.9 on 2026-01-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='s3_key',
            new_name='cloudinary_public_id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='s3_url',
            new_name='cloudinary_url',
        ),
    ]
